# Generated by Django 6.0.7 on 2026-07-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='director',
            name='birth_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
